project:
  type: book
  output-dir: docs
  
execute: 
  eval: false

book:
  title: "Data Publishing with `washr`"
  search: true
  cover-image: owd-cover.png
  favicon: owd-cover.png
  page-footer: 
    left: |
      Data Publishing with `washr` was written by the <a href="https://openwashdata.org/about#team">Open Science Team</a> at GHE
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>
  
  site-url: https://global-health-engineering.github.io/ghedatapublishing/
  repo-url: https://github.com/Global-Health-Engineering/ghedatapublishing
  repo-branch: main
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]

  chapters:
    - index.qmd
    - creating_repo.qmd
    - data_preparation.qmd
    - data_documentation.qmd
    - data_publication.qmd
    - troubleshooting.qmd

format:
  html:
    theme: pulse
  pdf:
    documentclass: scrreprt
    